baseURL: "https://xnzone.github.io/hugo-theme-bookstack/"
title: bookstack
paginate: 6
theme: hugo-theme-bookstack

menu:
  main:
    - identifier: search
      name: Search
      url: search/
outputs:
    home:
        - HTML
        - JSON